### ISSUE TITLE
How to set an inhomogeneous Neumann boundary condition ?

### ISSUE THREAD

**Issue by MSJavaScript** [kinnala/scikit-fem#1038]
For example, I want to solve the equation:
![BB](https://github.com/kinnala/scikit-fem/assets/23021127/038db9f2-5a2f-4cba-afc0-6fe22e602cd1)

If I use Euler backward formula, I get
![AA](https://github.com/kinnala/scikit-fem/assets/23021127/b24dbbe5-4dcc-4b07-956c-eb3f4bb1a92b)

How can I express v(0)·sin(u(0)) by scikit-fem ?

**Comment by MSJavaScript** [comment]
And in 2d case, for example, the domain is a square[0,1]×[0,1]. How can I set a boundary condition \partial u / \partial x = sin u ?

**Comment by kinnala** [comment]
Because of sin(u), what you have there is a nonlinear boundary condition. With implicit Euler, every step is still nonlinear. Nonlinear problems are solved using some iterative technique such as fixed point iteration or Newton's method.

After you have linearized the problem, you are able to represent boundary terms using the class FacetBasis. You would normally simply use FacetBasis in place of Basis to integrate over the boundary. Note that for 1D problem the boundary means 0D i.e. point evaluation and that's how inhomogeneous boundary condition is represented in your example.

You could also first try a simpler linear inhomogeneous Neumann BC such as u'(1) = 1.

**Comment by MSJavaScript** [comment]
@kinnala Oh, I know where is wrong. To eliminate the warning of splu, I convert the matrix to csc_matrix.
M1 = csc_matrix(asm(F2, ib) + dt * asm(F1, ib))
M2 = csc_matrix(asm(F2, ib))
However, this transpose the matrix, so the result is wrong.
Thanks for your help. : )
