### ISSUE TITLE
meshio breaks in numpy 2.0

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#1089]
A new version of numpy is coming soon. I did some tests and it seems that all code within scikit-fem will survive quite nicely. However, scikit-fem will probably break due to dependencies:
- meshio has not been active for two years and breaks in numpy 2.0 due to removed features being used within meshio codebase
- matplotlib currently has numpy<2 so this might save the above issue for some time

Possible remedies:
- It would be possible to set numpy<2 here and wait, but I don't have high hopes for meshio being fixed quickly (39 PR's, last PR merged 2 years ago).
- Remove meshio (too much work and too sudden change).
- Fork meshio and fix numpy==2

**Comment by gdmcbain** [comment]
Oh no, what a disaster! meshio was so active too, back when it was adopted here, and for a good while after that. I haven't been using finite elements at all myself since 2022, although I imagine I will again one day and then can't imagine how I'd get by without meshio. Are people using anything else instead?  I'd say the best course would be to fork it but it might be a busy job maintaining it. I did fork pygmsh (when it suddenly diverged, breaking backward compatibility) and pacopy (when it suddenly had a retrospective license change, supposedly even covering my own contributions, which didn't seem right) for use in my own projects, but only on GitHub, not on PyPI.  
   Hmm&hellip;

**Comment by kinnala** [comment]
A new version of meshio was released which fixes this issue.
