### ISSUE TITLE
Load from url?

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#109]
I don't know any "real" use case for this, but while I was creating a quick example today I wrote the following code:
```python
import tempfile
from urllib.request import urlopen

with tempfile.NamedTemporaryFile(suffix='.msh', delete=False) as temp:
    temp.write(urlopen("https://raw.githubusercontent.com/kinnala/scikit-fem/master/docs/examples/box.msh").read())
    temp.flush()
    m = MeshTet.load(temp.name)
```

Then I thought why not allow loading meshes from urls directly in `Mesh.load`? Maybe via `Mesh.load("https://...", url=True)` so that it is not done by accident.

**Comment by gdmcbain** [comment]
My first though was to wonder whether there wasn't already something in Python that covered this.  My second was that it might fit better upstream in meshio.read.  The other option that might be good is a buffer; like `filepath_or_buffer` in [`pandas.read_csv`](http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_csv.html#pandas.read_csv).

As to the use-case: yes, I definitely envisage an online repository of meshes, not necessarily specific to scikit-fem but open to any finite-element code, like the [Matrix Market](https://math.nist.gov/MatrixMarket/).  [Meshzoo](https://github.com/nschloe/meshzoo) is nice but that's for scripts that generate meshes rather than generated meshes.

**Comment by gdmcbain** [comment]
Indeed, the docstring for [`pandas.read_csv`](http://pandas-docs.github.io/pandas-docs-travis/generated/pandas.read_csv.html#pandas.read_csv) states:

> Either a path to a file (a str, pathlib.Path, or py._path.local.LocalPath), URL (including http, ftp, and S3 locations), or any object with a read() method (such as an open file or StringIO).
