### ISSUE TITLE
Support for Shell/Surface Meshes

### ISSUE THREAD

**Issue by NiklasFreymuth** [kinnala/scikit-fem#1121]
Hey all,

I am trying to use shell/surface meshes, i.e., 2D manifold meshes embedded in 3D space to model thin structures. I have my meshes available as .vtk files, but can not find any way to use them in scikit-fem.
Does scikit-fem currently support shell or surface meshes? If so, is there an example on how to use interface and use them?
If not, are there any plans to include this feature in the future? It would be helpful to know if this is on the roadmap, and what would potentially be required to make this work.

Thanks in advance!

**Comment by kinnala** [comment]
There is no proper support. I have no plans for studying shells myself. Some people have asked about this before, see Discussions.

I don't have a good overview of the problem type to know what people might use these meshes and element types for. Is it mainly shell theory (elasticity) or also something else?

We have a way to define bilinear forms over surfaces (FacetBasis). However, it is currently strictly restricted to boundaries of tetrahedral or hexahedral meshes. This is because we do not have separate surface basis functions and mappings, everything is defined using the volume basis functions restricted on the surface.

This way it is possible to hack together surface PDEs but it is slightly clumsy to have a single layer of volume elements to just integrate on its surface.

**Comment by NiklasFreymuth** [comment]
Thanks a lot for the quick reply!

I somehow missed the discussion on shell/midsurface meshes. I'll see if using the surface of a volumetric mesh is possible for my application, but it sounds like it could work.
