### ISSUE TITLE
stokes example ex18 fails

### ISSUE THREAD

**Issue by lukeolson** [kinnala/scikit-fem#270]
The stokes example https://kinnala.github.io/scikit-fem-docs/examples/ex18.html
fails:

```
 ○ python3 stokes.py
Traceback (most recent call last):
  File "stokes.py", line 36, in <module>
    uvp[np.setdiff1d(np.arange(K.shape[0]), D)] = solve(*condense(K, f, D=D))
ValueError: shape mismatch: value array of shape (3165,) could not be broadcast to indexing result of shape (2901,)
```

Changing this to `uvp = solve(*condense(K, f, D=D))` completes, but I'm not sure what the original code was attempting to do here.

**Comment by gdmcbain** [comment]
Indeed.

The source code listed in that example is out of date with respect to the latest sources
https://github.com/kinnala/scikit-fem/blob/d5e9a91101066a13a5ef5244c97832038d972571/docs/examples/ex18.py.

**Comment by gdmcbain** [comment]
The `diff -c` is quite extensive; `wc -l` gives 42 lines which is half the length of the script.

**Comment by gdmcbain** [comment]
The specific error that you hit is that the solution line can now be written more simply.

https://github.com/kinnala/scikit-fem/blob/d5e9a91101066a13a5ef5244c97832038d972571/docs/examples/ex18.py#L35

**Comment by gdmcbain** [comment]
> Changing this to `uvp = solve(*condense(K, f, D=D))` completes, but I'm not sure what the original code was attempting to do here.

What happened is that `solve` used only to return the degrees of freedom actually solved for, i.e. excluding those fixed by essential boundary conditions.  Nowadays, `condense` returns, besides the condensed matrix and right-hand side vector, also information on how to reconstruct the full solution.

This happened in #228.

The old code

https://github.com/kinnala/scikit-fem/blob/37ca85313ae977e9fa699ab8d4c8a76796fc98db/docs/examples/ex18.py#L34-L36

had to explicitly index where in the complete solution vector the unconstrained degrees of freedom had to go.

In this example, `D` is for Dirichlet and both components of velocity are zero on the wall.  The unconstrained degrees of freedom are the rest of the velocity and all of the pressure.  This was found with `numpy.setdiff1d`, though there's also a `GlobalBasis` method that encapsulates this. 

https://github.com/kinnala/scikit-fem/blob/61c547ae2a13812cf2af3f5d8995262d2e4c9a41/skfem/assembly/global_basis/global_basis.py#L119-L123

**Comment by lukeolson** [comment]
Thanks -- the updated example works fine for me.

(nice package!)

**Comment by gdmcbain** [comment]
Thank you and thank you for reporting.

**Comment by kinnala** [comment]
Updated the docs.
