### ISSUE TITLE
More helpful error message

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#308]
When trying to initialize `InteriorBasis` with obviously incompatible mesh and element (or any `Basis` for that matter), I get
```
---> 44 Ib = InteriorBasis(M, E)
     45 fb = FacetBasis(m, e)
     46 Fb = FacetBasis(M, E)

~/src/scikit-fem/skfem/assembly/basis/interior_basis.py in __init__(self, mesh, elem, mapping, intorder, elements)
     87 
     88         """
---> 89         super(InteriorBasis, self).__init__(mesh, elem, mapping, intorder)
     90 
     91         self.X, self.W = get_quadrature(self.refdom, self.intorder)

~/src/scikit-fem/skfem/assembly/basis/basis.py in __init__(self, mesh, elem, mapping, intorder)
     41                 for jtr in range(self.element_dofs.shape[0]):
     42                     self.doflocs[itr, self.element_dofs[jtr]] =\
---> 43                         doflocs[itr, :, jtr]
     44 
     45         self.mesh = mesh

IndexError: index 6 is out of bounds for axis 2 with size 6
```
which is not a helpful error message. We could add, e.g., to `ElementQuad[0-2]` objects the attribute `compatible_with = [MeshQuad]` so that `Basis` constructor can check the compatibility.

**Comment by gdmcbain** [comment]
#343 is good.

> We could add, e.g., to ElementQuad[0-2] objects the attribute compatible_with = [MeshQuad] so that Basis constructor can check the compatibility.

As is this.

Also, what about going the other way?  What about giving the subclasses of `Mesh` a way to compatible elements?  Typically one defines first a mesh and then an element, should the second step be facilitated?  A first step might be to register all elements compatible with the subclass of Mesh.  Further, what about offering the Lagrangian P1, or P(n), for a given mesh, if there is one; that would facilitate scripts less dependent on dimension, e.g. Mesh.load a mesh from a file and it might contain a MeshLine, MeshTri, or MeshTet, instantiate the P1 element, construct a basis, and assemble & solve Δ _u_ = 1 in _Ω_ with _u_ = 0 on ∂ _Ω_.  A common workflow is to develop in two dimensions and then switch to three for application.  

I was also thinking of something like this for encapsulating Taylor–Hood elements #241, since there is a TH element for each of the five subclasses of Mesh.  (Or will be once we have `ElementHex2` #327.)

The use of the word ‘register’ here is suggested by :

https://github.com/nschloe/meshio/blob/d5c3a9acbd9a1aab3ad707141760c79e22df6159/meshio/_helpers.py#L15-L21
