### ISSUE TITLE
Reproducibility of the meshes in the test suite

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#310]
I bumped into an issue where my laptop's Gmsh 4.5.1 and the test suite Gmsh 4.4.0 were producing different results. I circumvented this in #305 by saving the mesh generated by my laptop to a file, committing it and then loading that file if present.

Should we modify also other examples that generate meshes to save them in order to minimize version dependencies in the test suite?

**Comment by gdmcbain** [comment]
I noticed this too the other day when using `pip install gmsh-sdk` to install Gmsh, as mentioned in #180. Without asking pip for a specific version, this gives the latest gmsh-sdk and its coresponding Gmsh, 4.5.1.

In my case, the failure was only in ex27, the Navier-Stokes example, and was due to a very small change in the numerical solution—very small physically but bigger than the tolerance specified in the test. I think it's appropriate in such a case to loosen the tolerance.
