### ISSUE TITLE
Document how DOF's are handled

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#429]
From #426 

> The library do provide a way to handle Dirichlet boundary conditions by elimination. This shall be at least mentioned. I imagine that the treatment of more complex conditions, such as multiple points constraints in mechanics, have to be treated by hand after the assembly, isn't it ?

- [x] Discuss boundary conditions in the paper.

> Following the previous remark, it is not clear how the library could be used in this way. For example, is the mesh connectivity clearly described (how the unknowns are numbered) ?

- [x] Add a page to Sphinx doc describing how DOF's work.

**Comment by gdmcbain** [comment]
How would &lsquo;multiple points constraints&rsquo; be handled?  Is that like a rigid strut on a elastic body?

I guess one approach is Lagrange multipliers #150.  These are pretty easy to handle.  It is by hand, I suppose, but then the operators and vectors exposed by scikit-fem are just SciPy sparse matrices and NumPy ndarrays, so that facilitates that.

For elimination, the more general idea behind `skfem.condense` is that the unknown `x` can be expressed as `U @ u + K @ k` for (narrow) rectangular arrays `U` and `K` with `len(x)` rows and known vector `k` so that `u` is the new shorter unknown vector.  The special case of `condense` is that `U` and `K` are composed by partitioning the columns of the identity matrix.  Then the condensed version of Ax=b is `(U.T @ A @ U) @ x = U.T @ (b - A @ K @ k)`, which generalizes 

https://github.com/kinnala/scikit-fem/blob/9c485745018a915ae683295a011f910228741352/skfem/utils.py#L253-L254

What's the nonlinear version of that?  If the problem is f(x) = 0 and the constraints imply x = g(u), where x is longer than u, then the Newton iteration is f'(g(u)) g'(u) du = - f(g(u)).  To render that square again does one act from the left with g'(u).T?  That is, 

    g'(u).T f'(g(u)) g'(u) du = - g'(u).T f(g(u))

Does that generalize the previous?   With g'(u) = U, f'(g(u)) = A, f(g(u)) = b - A K k.

I haven't thought about whether these can be encapsulated as general purpose utility functions like `condense`; I'm not sure what form `U` and `K @ k` or `f` and `g` would be known in in practice.

I suppose another common application of multiple points constraints is periodic boundary conditions?

If the boundary condition is just that one lot of degrees of freedom is pointwise equal  to another, then it should be easy to construct `U`, much as in `condense`; e.g. if N = 3 and the constraint is x[2] = x[0], then U = [[1, 0], [0, 1], [1, 0]].

**Comment by thelfer** [comment]
> I suppose another common application of multiple points constraints is periodic boundary conditions?
> 
> If the boundary condition is just that one lot of degrees of freedom is pointwise equal to another, then it should be easy to construct `U`, much as in `condense`; e.g. if N = 3 and the constraint is x[2] = x[0], then U = [[1, 0], [0, 1], [1, 0]].

It depends. Periodic boundary conditions can be treated by modifying the unknown connectivity, so that the related pair of nodes corresponds to the same unknowns. But this strategy limits the Representative Element Volume to be a cube, which leads to numerous meshing trouble.

With Lagrange multipliers, you may use non cubic periodic meshes which may require less refined elements.
