### ISSUE TITLE
Multipoint Constraints and new elements in scikit-fem

### ISSUE THREAD

**Issue by bhaveshshrimali** [kinnala/scikit-fem#436]
Hi Tom and Geordie,

First off, `scikit-fem` is a really cool tool for someone like me who prototypes a lot of FE calculations. So thanks for putting this together. I just began going through the examples and had a couple of questions: 

   * Is it possible to define new elements given the knowlege of the basis functions (which are `C0`) on the reference element? For instance, following the mini element https://github.com/kinnala/scikit-fem/blob/a6a17a2e165fd7bb0a06f6fda37c7be82043f187/skfem/element/element_tri/element_tri_mini.py#L7

I would like to implement the *conforming* Crouzeix-Raviart element as described in [4.13](http://archive.numdam.org/article/M2AN_1973__7_3_33_0.pdf) in the celebrated paper by Crouzeix and Raviart. Is this (i.e. defining the basis) the only step in the FE assembly pipeline that is needed for implementing new elements ?

  * I am interested in applying scikit-fem to solve problems with general periodic boundary conditions, which can be implemented using multipoint constraints. I have done this at a higher level in `Abaqus`, where the kinematics of nodes on the boundary is described using some reference nodes. However I am still looking at how to implement these within a FE code written in pure python (and also, sooner than later in `scikit-fem`). 

I wanted to know if there are plans to support these through a higher level interface such as in [dolfinx_mpc](https://github.com/jorgensd/dolfinx_mpc), i.e. assembling FE matrices for problems with constrained kinematics. 

Looking forward to your replies as well as picking up `scikit-fem` in the upcoming months. 

Thanks
Bhavesh

**Comment by gdmcbain** [comment]
Hello.  Thanks for these great questions!  I think the answers are all basically yes, but we won't really know if there are hidden hitches till we've tried.  And they're both very worthwhile, so let's get onto them.  I'll split them up into a couple of issues:
* conforming Crouzeix–Raviart #437
* multipoint constraints #438 
If you have some specific little example problems that would demonstrate each feature, do add them there, that would be most helpful (like the size and complexity of those in docs/examples, with the view to future inclusion there), but otherwise I'll come up with something hopefully apt.

**Comment by kinnala** [comment]
I'll close this. Let's continue in #437 and #438.
