### ISSUE TITLE
JAX

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#441]
[JAX](https://jax.readthedocs.io/en/latest/) was [mentioned](https://github.com/kinnala/scikit-fem/issues/439#issuecomment-661692621) in #439 as a possible way of automating something like FEniCS's `derivative` for calculating Jacobians in nonlinear problems; however, one user [noted](https://github.com/kinnala/scikit-fem/issues/439#issuecomment-661879996) that they

> could never manage to install jax on a windows machine in the past.

A successful reimplementation of ex10 which currently has a handwritten Jacobian

https://github.com/kinnala/scikit-fem/blob/85b83ec91a13b87e160326246246ab86d5ac63ae/docs/examples/ex10.py#L15-L19

using JAX was demonstrated in #440 .

**Comment by gdmcbain** [comment]
I tried installing JAX under Windows 10 using Miniconda3:
```shell
conda create -n jax
conda activate jax
conda install pip
pip install jax
```
but that didn't work; 
```shell
python -c "import jax"
```
raises
> ModuleNotFoundError: No module named 'jaxlib'

Then, seeing that jax is in [conda-forge](https://anaconda.org/conda-forge/jax), I tried:
```shell
conda deactivate
conda env remove -n jax
conda create -n jax
conda activate jax
conda install -c conda-forge jax
```
but that failed with
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: -
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError:
```

**Comment by bhaveshshrimali** [comment]
Thanks for trying @gdmcbain .  I think my history with trying to use jax on windows was limited to using either `pip` or building from source. Either of those do not seem to have been fixed in the meanwhile (they recommend WSL), and possibly not in works for the near future. 

> We support installing or building jaxlib on Linux (Ubuntu 16.04 or later) and macOS (10.12 or later) platforms. Windows users can use JAX on CPU via the Windows Subsystem for Linux. We're not currently working on native Windows support, but contributions are welcome (see [#438](https://github.com/google/jax/issues/438)).

But I have a spare linux machine where I can try experimenting with jax.

**Comment by kinnala** [comment]
I'd prefer not to actually depend on something like JAX.

On the other hand, trying it out revealed already how an interface utilizing these autodiff tools should look like. So maybe we can eventually provide some additional utilities so that it's easier to use JAX or autograd or similar tools in scikit-fem.

PS. Does it work in Docker?

**Comment by bhaveshshrimali** [comment]
> PS. Does it work in Docker?

I think it should. They do have a [Dockerfile](https://github.com/google/jax/blob/master/build/Dockerfile) on their page. I can test build an image today. Infact if it works with Docker then it's the easiest way out for users to try on windows (even otherwise containerizing would help keep everything clean). In fact pretty much the same approach FEniCS takes to it's windows support.

**Comment by bhaveshshrimali** [comment]
> > PS. Does it work in Docker?
> 
> I think it should.



Checked! And it's working. [demo container](https://hub.docker.com/repository/docker/bhaveshshrimali/skfem_jax) 
`docker pull bhaveshshrimali/skfem_jax:latest`.
