### ISSUE TITLE
Clarify the licensing of the examples

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#445]
> Part of the motivation for having those examples in that other repo rather than here was that I wasn't sure about the copyright or licensing status of the FEniCS originals; I'm not a lawyer.

I haven't been too worried about the licensing of the examples because they are separate from the main source code, depend on `skfem` proper and not the other way around.

Strictly speaking all examples that depend on, e.g., `pygmsh` are GPLv3 due to the strong copyleft feature. If you feel that we should be explicit about this, then we can simply add a comment to the docstring about the differing license.

Edit: By separate, I mean that when installing `skfem` via the main distribution channel, we distribute only the contents of the directory `skfem`:
```
(testenv) conda-shell-chrootenv:tom@tunkki:~/src/scikit-fem$ pip show scikit-fem -f | egrep '.py$'
  skfem/__init__.py
  skfem/assembly/__init__.py
  skfem/assembly/basis/__init__.py
  skfem/assembly/basis/basis.py
  skfem/assembly/basis/facet_basis.py
  skfem/assembly/basis/interior_basis.py
  skfem/assembly/dofs.py
  skfem/assembly/form/__init__.py
  skfem/assembly/form/bilinear_form.py
  skfem/assembly/form/form.py
  skfem/assembly/form/form_parameters.py
  skfem/assembly/form/functional.py
  skfem/assembly/form/linear_form.py
  skfem/element/__init__.py
  skfem/element/discrete_field.py
  skfem/element/element.py
  skfem/element/element_composite.py
  skfem/element/element_global.py
  skfem/element/element_h1.py
  skfem/element/element_hcurl.py
  skfem/element/element_hdiv.py
  skfem/element/element_hex/__init__.py
  skfem/element/element_hex/element_hex1.py
  skfem/element/element_hex/element_hex_s2.py
  skfem/element/element_line/__init__.py
  skfem/element/element_line/element_line_hermite.py
  skfem/element/element_line/element_line_mini.py
  skfem/element/element_line/element_line_p1.py
  skfem/element/element_line/element_line_p2.py
  skfem/element/element_line/element_line_pp.py
  skfem/element/element_quad/__init__.py
  skfem/element/element_quad/element_quad0.py
  skfem/element/element_quad/element_quad1.py
  skfem/element/element_quad/element_quad2.py
  skfem/element/element_quad/element_quad_bfs.py
  skfem/element/element_quad/element_quad_dg.py
  skfem/element/element_quad/element_quad_s2.py
  skfem/element/element_quad/element_quadp.py
  skfem/element/element_tet/__init__.py
  skfem/element/element_tet/element_tet_mini.py
  skfem/element/element_tet/element_tet_n0.py
  skfem/element/element_tet/element_tet_p0.py
  skfem/element/element_tet/element_tet_p1.py
  skfem/element/element_tet/element_tet_p2.py
  skfem/element/element_tet/element_tet_rt0.py
  skfem/element/element_tri/__init__.py
  skfem/element/element_tri/element_tri_argyris.py
  skfem/element/element_tri/element_tri_dg.py
  skfem/element/element_tri/element_tri_mini.py
  skfem/element/element_tri/element_tri_morley.py
  skfem/element/element_tri/element_tri_p0.py
  skfem/element/element_tri/element_tri_p1.py
  skfem/element/element_tri/element_tri_p2.py
  skfem/element/element_tri/element_tri_rt0.py
  skfem/element/element_vector_h1.py
  skfem/helpers.py
  skfem/importers/__init__.py
  skfem/importers/meshio.py
  skfem/io/__init__.py
  skfem/io/json.py
  skfem/io/meshio.py
  skfem/mapping/__init__.py
  skfem/mapping/mapping.py
  skfem/mapping/mapping_affine.py
  skfem/mapping/mapping_isoparametric.py
  skfem/mapping/mapping_mortar.py
  skfem/mesh/__init__.py
  skfem/mesh/mesh.py
  skfem/mesh/mesh2d/__init__.py
  skfem/mesh/mesh2d/mesh2d.py
  skfem/mesh/mesh2d/mesh_quad.py
  skfem/mesh/mesh2d/mesh_tri.py
  skfem/mesh/mesh3d/__init__.py
  skfem/mesh/mesh3d/mesh3d.py
  skfem/mesh/mesh3d/mesh_hex.py
  skfem/mesh/mesh3d/mesh_tet.py
  skfem/mesh/mesh_line.py
  skfem/models/__init__.py
  skfem/models/elasticity.py
  skfem/models/general.py
  skfem/models/helpers.py
  skfem/models/poisson.py
  skfem/quadrature.py
  skfem/utils.py
  skfem/version.py
  skfem/visuals/__init__.py
  skfem/visuals/matplotlib.py
```

_Originally posted by @kinnala in https://github.com/kinnala/scikit-fem/issues/439#issuecomment-665493939_

**Comment by kinnala** [comment]
I propose that we add an explicit license to the docstring of each file (that differ from the main BSD 3-clause), and also add these to the list of exceptions in `LICENSE.md`.

Here is an example:
```
Copyright 2018-2020 scikit-fem developers
    
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
```
This would apply to the examples depending directly on GPLv3 software such as `pygmsh`.

**Comment by gdmcbain** [comment]
Yes, we were somewhat wrongfooted here.  There's quite a [history](https://github.com/nschloe/pygmsh/commits/master/LICENSE.txt) to the licensing of pygmsh.  When those examples were written and committed, pygmsh wasn't under a GPL.  It was under the MIT licence until 2020-04-10 and https://github.com/nschloe/pygmsh/commit/95c481e1904657c4820d8fe7c99e893bbda8d14f#diff-61e0bdf7e1b43c5c93d9488b22e04170 'change version to GPLv3'.  Before that, until 2015-10-28, it had been BSD-3, from 2013-10-10 https://github.com/nschloe/pygmsh/commit/4c3c0d9dda5022f426a21f498b99f5395c759eff#diff-7116ef0705885343c9e1b2171a06be0e.  I'm not sure what that means for the status of code relying on pre-GPL pygmsh, or how it applies to contributions to pygmsh from before April.  ([My 37 commits](https://github.com/nschloe/pygmsh/commits?author=gdmcbain) are all from the MIT era.)

Maybe because pygmsh does rely on Gmsh which has been GPL for as long as I can remember, it should always have been GPL?  I didn't read any rationale for the changes to pygmsh's licence.

Anyway your proposal sounds eminently reasonable.

I had been thinking of replacing scikit-sparse with `scipy.sparse.linalg.splu` in [ex19 &lsquo;Heat equation&rsquo;](https://scikit-fem.readthedocs.io/en/latest/listofexamples.html#example-19-heat-equation); I suspect it will work just fine.
