### ISSUE TITLE
Reimplement *_satisfying in a more generic fashion

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#51]
The methods named:

- Mesh3D.nodes_satisfying
- Mesh3D.facets_satisfying
- Mesh3D.elements_satisfying

could be implemented in a generic fashion for both 2D and 3D meshes and moved to Mesh superclass. They already look very similar: the tuple unpack notation via * could be used to make the implementation equivalent.

**Comment by gdmcbain** [comment]
Oh, another idea: if a point in the line, plane, or space were represented by a single grouped entity rather than the separated Cartesian coordinates. `ndarray` is the obvious choice here as this correspondence to the columns of `Mesh.p`.  Would thus be another way of achieving dimension-independent code?

**Comment by kinnala** [comment]
I'm sorry I missed your idea. The reason why columns of p correspond to points is mostly historical but also in assembly we require efficient slicing of all x-coordinates. Default memory ordering of NumPy makes this more efficient in terms of caching.

**Comment by gdmcbain** [comment]
Oh, no, I didn't mean columns as opposed to rows. (I agree with that choice, by the way.) I just meant that a point might be passed as a single argument rather than `dim` arguments, one per coordinate. As far as that goes it could be a tuple, list, ndarray, dict, object, whatever, but `ndarray` is probably best.

A point (say the i-th) is naturally obtained from a `skfem.Mesh`, however, as `mesh.p[:, i]`, the i-th column of `mesh.p`, which is an `ndarray` of shape `(dim,)`. Isn't that the form that the points will be in already when they're passed to the lambda function? (I didn't check, I just assumed that they'd be sliced out of `mesh.p`.)

Envoyé depuis ProtonMail mobile

-------- Message d'origine --------
