### ISSUE TITLE
How can I insert the Coordinate and Element arrays in a simple poisson problem in scikit fem? 

### ISSUE THREAD

**Issue by nikosmatsa** [kinnala/scikit-fem#529]

**Comment by nikosmatsa** [comment]
Want to implement a simple poisson problem $-\Delta u = 10$ in a L shape domain given two matrices with coordinates and elements as shown in the link below (my so far effort).The problem is how can I insert them in order to have these specific coordinates?  

https://github.com/nikosmatsa/Finite-Differences-Methods-for-PDE-/blob/main/Finite%20Element%20.ipynb

**Comment by kinnala** [comment]
Try feeding those to the default constructor of `MeshTri` as follows:
```python
MeshTri(coordinates.T, elements.T - 1)
```
Note that indices in Python are zero-based.

**Comment by nikosmatsa** [comment]
it worked.

but I don't know if in the simple parabolic problem $$(u_{t}-u_{xx}=10)$$, with the same coordinates are right for (Crank Nicolson Method) below the Poisson problem 



https://github.com/nikosmatsa/Finite-Differences-Methods-for-PDE-/blob/main/Finite%20Element%20.ipynb

**Comment by gdmcbain** [comment]
No?  Looks O. K., I think?  It's pretty much the same as [ex19](https://scikit-fem.readthedocs.io/en/latest/listofexamples.html#example-19-heat-equation), isn't it?

**Comment by nikosmatsa** [comment]
I plot(m,u) not plot(m,x) as in poisson.

**Comment by gdmcbain** [comment]
Ah, O. K., yes, sorry.  I went with `u` in ex19 rather than `x` as in, e.g., ex01, to avoid confusion with the `x` coordinate as in, e.g., ex03 or ex14, though of course `x` is standard for the unknown in linear algebra; e.g. [`scipy.sparse.linalg.spsolve`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.spsolve.html).  Naming things is hard&hellip;

**Comment by nikosmatsa** [comment]
But again i need confirmation.as my heat equation ut-uxx=10 is correctly implemented given these coordinates
'

**Comment by gdmcbain** [comment]
I'm not sure that I follow.  Do you mean that you only want conduction in the *x*-direction but on the two-dimensional ell-shaped domain?  I'm not sure how well posed that is mathematically or physically, but if so don't use [`skfem.models.poisson.laplace`](https://github.com/kinnala/scikit-fem/blob/b39cf61914f0bb325f0d1196fdf8407019b3769d/skfem/models/poisson.py#L7-L9) 
```python
@BilinearForm
def laplace(u, v, w):
    return dot(grad(u), grad(v))
```
and instead define a new `BilinearFrom` like it; e.g.
```python
@BilinearForm
def xlaplace(u, v, w):
    return u.grad[0] * v.grad[0]
```
This works O. K. in ex19.

**Comment by nikosmatsa** [comment]
How you implement the heat equation ut-uxx=10 in scikit fem ?

**Comment by gdmcbain** [comment]
On what domain and with what boundary conditions?

Do you want to solve it on a segment like 0 < *x* < 1 with say *x*=0 at each end?  That would be easy enough. I can modify ex19 to show that, if that's what's required.

Or on the L? There the boundary conditions are trickier because of the degenerate anisotropy of the conduction operator. For that, boundary conditions can only be specified on parts with the normal in the *x*-direction, not all around.

**Comment by kinnala** [comment]
> How you implement the heat equation ut-uxx=10 in scikit fem ?

There is an example here: https://scikit-fem.readthedocs.io/en/latest/listofexamples.html#example-19-heat-equation

**Comment by nikosmatsa** [comment]
my effort for the parabolic pde based on the example 19 is on the link below.i don't know if it right and also I don't know how to plot it.(I don't want this animation just a plot and I am fine)

https://github.com/nikosmatsa/Finite-Differences-Methods-for-PDE-/blob/main/parabolic%20fem%20.ipynb

**Comment by kinnala** [comment]
There should be a call to solve somewhere. Also, possibly an iteration over time steps of some sort? I suggest that you try to write down the iteration first on pen and paper, and then try to transform that into code. That's at least how I usually approach it.

**Comment by kinnala** [comment]
Note that we don't have any helper functions for time integration yet. That would be a welcome improvement though, e.g., `skfem.ivp` or something.

**Comment by gdmcbain** [comment]
O. K., so looking at parabolic%20fem%20.ipynb, I see that &lsquo;uxx&rsquo; is the usual two-dimensional laplacian <i>&Delta;u = &nabla;&sup2;u = u<sub>,xx</sub> + u<sub>,yy</sub> = &part;&sup2;u/&part;x&sup2; + &part;&sup2;u/&part;y&sup2; </i> and my fears about well-posedness are unfounded; then as @kinnala writes we have the example in ex19.  Further:

> There should be a call to solve somewhere. Also, possibly an iteration over time steps of some sort? 

In ex19, `solve` is called by [`step`](https://github.com/kinnala/scikit-fem/blob/b39cf61914f0bb325f0d1196fdf8407019b3769d/docs/examples/ex19.py#L79-L85)

```python
def step(t: float,
         u: np.ndarray) -> Tuple[float, np.ndarray]:
    u_new = np.zeros_like(u)              # zero Dirichlet conditions
    _, b1 = condense(csr_matrix(A.shape),  # ignore condensed matrix
                     B @ u, u_new, D=boundary, expand=False)
    u_new[interior] = backsolve(b1)
    return t + dt, u_new
```

and the iteration over time steps is done by [`evolve`](https://github.com/kinnala/scikit-fem/blob/b39cf61914f0bb325f0d1196fdf8407019b3769d/docs/examples/ex19.py#L88-L93) which repeatedly calls `step` (very much in the manner of an [iterated function](https://en.wikipedia.org/wiki/Iterated_function)).
```python
def evolve(t: float,
           u: np.ndarray) -> Iterator[Tuple[float, np.ndarray]]:

    while np.linalg.norm(u, np.inf) > 2**-3:
        t, u = step(t, u)
        yield t, u
```

In turn, in ex19, `evolve` is called by `FuncAnimation`, which also calls `update` to do something with the new snapshot; specifically to add a frame to the animation.

In general, I'd recommend keeping something like the `solve`, `step`, `evolve`, trio but I'll start a new issue to discuss `skfem.ivp`.

Meanwhile, you might like to look at an older version of ex 19, [665847e](https://github.com/kinnala/scikit-fem/blob/665847e86536c2fcd6d7275a3e64d9566516bf7a/docs/examples/ex19.py) which hadn't yet separated the `step` and `evolve` functions and just plotted each snapshot using `mesh.plot`, repeatedly calling solve inside a while-loop.  (This version of the example probably won't run any more; I can't get `sksparse` to install on my machine, for example, it's no longer maintained.)

In the current version of ex19, you might try, instead of `FuncAnimation`, something like:
```python
for t, u in evolve(0., u_init):
        print(t, max(u))
```

**Comment by nikosmatsa** [comment]
for 1D my parabolic is easy implement it in python with spicy.integrate (gauss quadrature) 

`import numpy as np
import matplotlib.pyplot as plt
from scipy import integrate
    
M = 10 #points in x
L = 1 #endpoint
x = np.linspace(-L,L,M+1)
h = x[1]-x[0]
    

    
    
def stiffassembly(M):
    diag = np.zeros(M-1) #x_1,...,x_{M-1} (M-1)
    offd = np.zeros(M-2) #off diagonal terms
    for i in range(1,M):
        diag[i-1] = 1/h +1/h
    
    for k in range(1,M-1):
        offd[k-1] = -1/h
    
    A = np.diag(offd,-1) + np.diag(diag,0) + np.diag(offd,+1)
    return A
    
    
def massmatrix(N):
    diag = np.zeros(N-1) #x_1,...,x_M-1 (M-1)
    subd = np.zeros(N-2) 
    supr = np.zeros(N-2)
        
    for i in range(1,N):
        diag[i-1] = (h + h)/3
    for k in range(1,N-1):
        supr[k-1] = h/6
        subd[k-1] = h/6
    
        M = np.diag(subd,-1) + np.diag(diag,0) + np.diag(supr,+1)
    return M
    
    
    
def f(x):
    return 10
    
    
def load(M):
    load = np.zeros(M-1)
    for k in range(1,M):
        load[k-1] = integrate.quad(lambda w: f(w)*(1/h)*(w-x[k-1]),x[k-1],x[k])[0] + integrate.quad(lambda w: f(w)*(1/h)*(x[k+1]-w),x[k],x[k+1])[0]
        
    return load
    
    
u = np.linalg.solve(+stiffassembly(M) + massmatrix(M),load(M))
U = np.r_[0,u,0]
plt.plot(x,U)
plt.show()`



but I want to implement it with scikit fem

**Comment by gdmcbain** [comment]
Oh, so you are in one dimension.  One-dimensional problems in scikit-fem use `MeshLine` and e.g. `ElementLineP1` or `ElementLineP2`.  There's a one-dimensional Poisson equation in [ex15](https://scikit-fem.readthedocs.io/en/latest/listofexamples.html#example-15-one-dimensional-poisson-equation).  You'll see that most of the code is pretty independent of dimension except of course the plotting.

**Comment by kinnala** [comment]
Please open a new issue if there are further questions. I think the original question in the title has been now answered.
