### ISSUE TITLE
Support method chaining in Mesh

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#536]
A proposition:
- [x] return `self` in `Mesh.scale`, `Mesh.translate`, and `Mesh.refine` to support chaining them
- [x] deprecate `Mesh.remove_elements` and implement `Mesh.prune` with similar functionality which returns `self`
- [ ] deprecate `Mesh.mirror`
- [ ] implement `Mesh.flip_vertical` and `Mesh.flip_horizontal` that return `self`

**Comment by gdmcbain** [comment]
Definitely yes.

Personally I prefer, wherever possible, pure functions and immutable data structures, but method chaining is a good step towards enabling that kind of style.  I mean I would not recommend adhering to immutability in cases like assembling a global vector from Dirichlet and solved-for parts as in

https://github.com/kinnala/scikit-fem/blob/6e31b46e1d11d12d93798405d38c3764a18a8f72/skfem/utils.py#L178-L179

but for new methods I might try to think about whether immutability and purity were reasonable.

From Python 3.7 (I think we're still supporting 3.6 though) there is [`dataclasses.dataclass`](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass) with `frozen=True` which enables [internal hashing](https://docs.python.org/3/reference/datamodel.html#object.__hash__) which enables [`functools.lru_cache`](https://docs.python.org/3/library/functools.html?highlight=functools%20lru_cache#functools.lru_cache) which can be used with the [`property`](https://docs.python.org/3/library/functions.html#property) decorator to make what I think of as lazy attributes: object attributes that aren't computed unless and until required but unlike simple properties in that they're cached rather than recomputed each time.

(On looking up those links just now, I see that the core Python Standard Library developers have found that idea useful enough that they included [`functools.cached_property`](https://docs.python.org/3/library/functools.html?highlight=functools%20lru_cache#functools.cached_property) in 3.8.)

I've being thinking about whether that kind of idea might work for `Mesh` properties like `t2f`, `f2t`, &c., to replace

https://github.com/kinnala/scikit-fem/blob/6e31b46e1d11d12d93798405d38c3764a18a8f72/skfem/mesh/mesh2d/mesh_tri.py#L97

in the constructor.  I wondered whether those were expensive to calculate and yet not always required; e.g. in something like the intermediate steps of

https://github.com/kinnala/scikit-fem/blob/6e31b46e1d11d12d93798405d38c3764a18a8f72/docs/examples/ex01.py#L5

**Comment by gdmcbain** [comment]
>  deprecate Mesh.remove_elements and implement Mesh.prune with similar functionality which returns self

Is the idea here to use [`Mesh._reix`](https://github.com/kinnala/scikit-fem/blob/406e60a4bf251e535ca514d016f3f7100629e5f8/skfem/mesh/mesh.py#L437-L442) from #530?

**Comment by gdmcbain** [comment]
What's implied in the renaming `remove_elements` &rarr; `prune`?

By 

> Mesh.prune with similar functionality which returns self

do you mean that `prune` should mutate self and then return self?  Currently `remove_elements` already returns the new `Mesh`.

**Comment by gdmcbain** [comment]
Ditto for the two replacements for `Mesh.mirror`.

**Comment by kinnala** [comment]
> Personally I prefer, wherever possible, pure functions and immutable data structures, but method chaining is a good step towards enabling that kind of style.

So, in practice, you'd like all of these methods to return a copy instead of modifying `self`? If we decide on this approach, then we should go directly for that instead of returning `self` in the meanwhile because going from `self` to something else is another backwards-incompatible change.

Pros: `Mesh` would be more immutable and, e.g., `Mesh.refine()` after initializing `InteriorBasis` from the `Mesh` would not break the `InteriorBasis`. Note that I don't want to make a copy of the `Mesh` when initializing `InteriorBasis` because of the performance implications.

Cons: Running, e.g., `scale` would require reinitializing `Mesh` which is potentially costly in large meshes. As you've mentioned, this could be minimized by caching `Mesh.t2f`. I've been also playing with an idea of memory-optimizing `submeshes` and `boundaries` by making the underlying data structure different.

I think the pros may outweigh the cons. However, this requires some coordination, e.g., how can we minimize backwards-incompatibility. AFAIC adding a return value to a method which does not have one (i.e. returns None) will not require a major version increment. What do you think?

Also, are @lru_cache and similar complexities really required here, as it may be sufficient to initially set `self._t2f = None` and make the following property:
```python
@property
def t2f(self):
    if self._t2f is None:
        self._t2f = ...
    return self._t2f
```

**Comment by kinnala** [comment]
> do you mean that `prune` should mutate self and then return self?

This is what I was originally thinking but if we want to make entire `Mesh` immutable, then we can forget about it.

**Comment by kinnala** [comment]
I realized that changing `Mesh.refine` to return a copy is actually quite a big change because `Mesh.refine` is used literally everywhere and it is assumed that we can simply call `m.refine()`. Maybe as you say that returning `self` is a reasonable intermediate step after all. Then we can think at some point if rewriting the entire `Mesh` system is worth achieving the immutability.

**Comment by gdmcbain** [comment]
I agree with your assessment and summary of the pros and cons.  Immutability and purity are nice in general but in a finite element library great care has to be taken to preserve and improve performance.

> Note that I don't want to make a copy of the Mesh when initializing InteriorBasis because of the performance implications.

Quite so.  I think the Basis is already more or less immutable, isn't it?  I mean its immutability isn't enforced&mdash;it never really is in Python, except for frozen dataclasses&mdash;but I don't think there are any obvious ways to mutate it or examples in which bases are mutated.  If the Mesh attribute of a Basis were mutated, that would invalid the Basis, but hopefully that should be obvious.  When it might not be obvious is when a Mesh is inadvertantly mutated.  Those are what I'd like to avoid.  They can lead to nasty bugs like nschloe/meshio#504 and nschloe/meshio#539.

**Comment by gdmcbain** [comment]
> I realized that changing Mesh.refine to return a copy is actually quite a big change because Mesh.refine is used literally everywhere and it is assumed that we can simply call m.refine().

Yeah.  It is used in a lot of examples.  It isn't necessary in most of them; the ones that are lines, rectangles, or cuboids, they're easily enough generated with `.init_tensor`.  A more significant usage is in `MeshTri.init_circle` and `MeshTet.init_ball` (but they could both be easily changed internally to use the returned value).

Apart from established usage, is there any reason for `Mesh.refine` to be mutating the mesh passed in?  I don't think the refined mesh manages to preserve and reuse any of the significant attributes of the original does it?  If it needs to create new attributes, it's no more expensive to pack them into a new object, is it? 

Possible cases for mutating a Mesh might be `scale`, as mentioned (although that seems like something one would only do at the very beginning, to change units of length or something), or other kinds of deformation, preserving the connectivity of the mesh.  I'm not sure whether we have any examples of that other than for displaying linear elastic deformation as in ex03.  Currently that actually generates a new `MeshQuad` (with an attendant call to `._build_mappings`), rather than simply modifying `m.p`.  Were there to be more distortion of meshes (I don't think this is used in the hyperelastic example), one might think about separating the connectivity and geometry.  I think there was some work like that in #399, inspired by MFEM?

Anyway, I definitely don't want to do anything in a rush and am very hesitant to break anything.  (We have enough of that foisted on us from elsewhere in the ecosystem.)

**Comment by gdmcbain** [comment]
> Maybe as you say that returning self is a reasonable intermediate step after all. 

Yeah, I think so.  And changing wherever `.refine` or `.uniform_refine` is used so that it uses the returned value.  Then sometime in the indefinite future it might be safer to begin deprecating the reliance on mutation.

**Comment by gdmcbain** [comment]
> AFAIC adding a return value to a method which does not have one (i.e. returns None) will not require a major version increment. What do you think?

No, I wouldn't have thought so.  Although it did trip up the doctests in #537.  It doesn't break any existing code that worked.
