### ISSUE TITLE
Steps towards a "functional Mesh"

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#540]
We decided with @gdmcbain on the goal of having the public API of `Mesh` to be functional in the sense that none of the methods purposefully modify `self`. #536 and the corresponding PR #538 will eventually take care of `refine`, `scale`, `translate`, etc. by introducing `refined`, `scaled`, `translated` that return copies of the mesh. We will first use the new versions in the documentation and deprecate the old versions. Finally after a suitable time and a number of releases we will remove the original `refine`, `scale`, `translate`. There are immediate benefits to the functionality of `Mesh`, e.g., one cannot accidentally invalidate a `Basis` object by calling `Mesh.refine`.

However, there is a missing piece of the puzzle: `Mesh.define_boundary`. This was never such a huge success as one can simply provide `boundaries` dictionary to the constructor or then directly pass facet indices to `basis.get_dofs` or `basis.find_dofs`.

**Comment by gdmcbain** [comment]
> the goal of having the public API of Mesh to be functional 

Possible exception mentioned in #536:

> Possible cases for mutating a Mesh might be &hellip; deformation, preserving the connectivity of the mesh &hellip; one might think about separating the connectivity and geometry. I think there was some work like that in #399, inspired by MFEM?

This might be like introducing two new classes for the Connectivity and Geometry, both immutable and then having a Mesh, also immutable, have one of each as an attribute. Then if the Mesh is to be distorted, a new Mesh is created with the old Connectivity and a new Geometry.   All the expensive to recalculate attributes/properties like t2f belong to the Connectivity and so are automatically preserved.

**Comment by gdmcbain** [comment]
> However, there is a missing piece of the puzzle: Mesh.define_boundary.

In the same way as `class Mesh` might be divided up into `class Topology` and `class Geometry` (or hopefully with better names), perhaps the `boundaries` attribute (and similarly `subdomains`) might be separated from the object so that another new class (&lsquo;`Domain`&rsquo;?), again immutable, might have an immutable `Mesh` as an attribute and also `boundaries` and `subdomains`, which might be implemented as namedtuples rather than dicts so that they're less mutable too.

If `class Domain` were a frozen dataclass (which is impossible until Python <3.7 is dropped), an operation like `.define_boundaries` could be done with the [`dataclasses.replace`](https://docs.python.org/3/library/dataclasses.html#dataclasses.replace) module function, which returns a new immutable object based on an old one  just replacing those attributes that need changing.  While Python 3.6 is still supported, this idea can be implemented manually.

**Comment by kinnala** [comment]
These are all fantastic ideas. Basically `Mesh` would be a wrapper for `Topology`, `Geometry` and `Domain` with the few specialized constructors. The split in #536 is also very promising due to other reasons: it seems that I'm able to combine the logic of `_build_mapping` among several mesh types which will reduce the overall complexity and LOC.

**Comment by gdmcbain** [comment]
> Basically Mesh would be a wrapper for Topology, Geometry and Domain

I was thinking that:
* Mesh would be a wrapper for Topology and Geometry
* Domain would be a wrapper for Mesh, and Boundaries & Subdomains

The motivation for that second part is the
> missing piece of the puzzle: Mesh.define_boundary

if `Mesh.boundaries` is an attribute, then a `Mesh.define_boundary` method mutates the `Mesh` instance; if the `Mesh` instance and the `Boundaries` are both attributes of a `Domain` instance then the `Mesh` instance remains immutable and a new `Domain` is instantiated referring to it and a new `Boundaries` object.

But perhaps that's too much change and it would be better to keep `Mesh` as the most obvious class in user-level scripts?  Then having `Boundaries` and `Subdomains` as attributes of `Mesh` alongside `Topology` and `Geometry` should work, yes.  By `Domain` then you mean something including `Boundaries` and `Subdomains`?

What would go in `Geometry` besides what's currently in `Mesh.p`?  Not much at the moment that I can think of but maybe one day curves and surfaces?  (If say an edge of a triangle was supposed to adhere to a plane curve rather than just have its termini adhere to points, this becoming relevant, e.g., when the triangle is refined.)
