### ISSUE TITLE
apply Dirichlet conditions by setting rows to I, rhs to value

### ISSUE THREAD

**Issue by nschloe** [kinnala/scikit-fem#591]
For the first time, I'm looking at scikit-fem in a serious manner. Diving into it, I notice that the common way the "apply" Dirichlet conditions is to eliminate the respective entries from the matrix/rhs à la
```python
A, b = condense(A, b, I=mesh.interior_nodes())
```
I on the other hand would like to see those condition applied via setting the respective rows in `A` to diagonal `1` and `0` otherwise plus the respective rhs entry to the value. Something like
```python
apply_dirichlet(A, b, mesh.boundary_nodes(), vals)
```
perhaps. The resulting matrix has the same spectral properties as the condensed `A`, so the number of iterations with Krylov methods will be the same, too. Advantages of this approach include the fact that neither `A` nor `b` need to be rewritten in memory. Also, the solution will include the values of _all_ degrees of freedom, making postprocessing easier.

**Comment by gdmcbain** [comment]
G'day, Nico. 

There was a very brief reference to the alternative `apply_dirichlet` technique [a couple of years ago](https://github.com/kinnala/scikit-fem/issues/150#issuecomment-480118703) as part of a broader discussion of the many ways to deal with essential boundary conditions in the finite element method #150; as noted there, Ern & Guermond (2004) called it &lsquo;keeping the essential nodes&rsquo; (&sect;8.4.3) to distinguish it from &lsquo;eliminating the essential nodes&rsquo; (&sect;8.4.2).

 `skfem.utils.condense` was already here before I stumbled upon scikit-fem, so I can't speak of the original motivation, but I was pleased to find it as I had already been using this technique for some years in my own in-house finite element (& other) codes.  I first learned of it from comments by Roy Stogner on `libmesh-users`; here's a (slightly redacted) excerpt from my notes from 2012&ndash;2013:

> Many evolution problems for dynamical systems involve constraints on some of the unknowns, such as the pressure being specified at certain nodes in [incompressible fluid mechanics], or essential boundary conditions in the finite element method.

> A matrix-oriented representation of constraining dynamical systems by mapping degrees of freedom is suggested by Roy Stogner's comments on essential boundary conditions in the finite element method posted to the `libmesh-users` list under the thread [&lsquo;interaction between `subdomain_id` and dof constraints?&rsquo;](http://sourceforge.net/mailarchive/message.php?msg_id=28886234). Stogner discussed the case of a steady-state matrix problem *Kx* = *f*, subject to a constraint *x* = *Cy* + *h*; here *K* is some stiffness matrix, *x* the complete vector of nodal values, *f* the right-hand side forcing vector, *y* the vector of unknown nodal values, *h* a vector supplying nonzero nodal constraints (e.g. essential boundary conditions) and *C* a matrix mapping the free degrees of freedom into the complete nodal vector.

> The mapping technique is particularly useful for modal analyses since it does not introduce spurious eigenvalues as some other techniques do.  For example, to apply the built-in boundary conditions to the finite element [&hellip;] model, compare [&hellip;] which zeros the offdiagonal elements and puts ones on the diagonal in slots corresponding to the fixed degrees of freedom with [&hellip;] using the present technique.  The former generates one spurious mode with unit eigenvalue for each fixed degree of freedom. 

Now I do remember being very pleased at being able to avoid spurious eigenvalues as these had been a constant headache in some of my earlier work using orthogonal collocation methods; however this seems to be at odds with your claim about the preservation of the spectral properties.  Let me go back and check!

I think it should be pretty easy to implement `apply_dirichlet` and I think it would also be good to have it in `skfem.utils` (possibly with a name more descriptive of how it applies Dirichlet conditions seeing as it's only one way of doing it).  I'm afraid #150 hasn't had much attention lately, but I would very much like to see it completed in a comprehensive way, including `apply_dirichlet`, the penalty method (E. & G., &sect;8.4.4), &c., &c.  PRs welcome, of course!

**Comment by gdmcbain** [comment]
Rather than
```python
apply_dirichlet(A, b, mesh.boundary_nodes(), vals)
```
it should have the same signature as `condense`:
```python
enforce(A, b, vals, D=mesh.boundary_nodes())
```

**Comment by kinnala** [comment]
`A` is `scipy.sparse.csr_matrix`, so I think we need to do some low-level trickery using `A.data` and `A.indptr` to make it efficient. Another option would be to specify these values inside `asm` before even creating `scipy.sparse.csr_matrix`.

**Comment by nschloe** [comment]
Something like
```python
for i in dofs:
    matrix.data[matrix.indptr[i] : matrix.indptr[i + 1]] = 0.0
```
would set the rows to 0, but perhaps one can do better than the python loop here.

**Comment by gdmcbain** [comment]
Interesting, thanks.  I'm watching scipy/scipy#13746 now.  Yes, changing sparsity patterns is bad.

Ern & Guermond (ibid.) give some hints on implementation, I'll reread that.  (Although it's probably for compiled languages and so may not address the special needs of Python and `scipy.sparse`.)

And yes the makeshift solution, correct if not optimally efficient, would still be worthwhile for exploring the extent of 

> Advantages of this approach include the fact that neither `A` nor `b` need to be rewritten in memory. Also, the solution will include the values of all degrees of freedom, making postprocessing easier.

If the interface is correct, there's no problem improving the implementation later.

**Comment by kinnala** [comment]
Here is a proposition. First, I was looking into the following diff:
```diff
modified   skfem/assembly/form/bilinear_form.py
@@ -81,8 +81,8 @@ class BilinearForm(Form):
         # initialize COO data structures
         sz = ubasis.Nbfun * vbasis.Nbfun * nt
         data = np.zeros(sz, dtype=self.dtype)
-        rows = np.zeros(sz)
-        cols = np.zeros(sz)
+        rows = np.zeros(sz, dtype=np.int64)
+        cols = np.zeros(sz, dtype=np.int64)
 
         # loop over the indices of local stiffness matrix
         for j in range(ubasis.Nbfun):
@@ -98,6 +98,19 @@ class BilinearForm(Form):
                     dx
                 )
 
+        # dofs that will be modified
+        D = ubasis.mesh.nodes_satisfying(lambda x: x[0] == 0)
+
+        # zero rows
+        rows_mapping = np.ones(np.max(vbasis.N))
+        rows_mapping[D] = 0
+        data = rows_mapping[rows] * data
+
+        # ones to diagonal
+        data = np.concatenate((data, np.ones(len(D))))
+        rows = np.concatenate((rows, D))
+        cols = np.concatenate((cols, D))
+
         # TODO: allow user to change, e.g. cuda or petsc
         return self._assemble_scipy_matrix(
             data,
```
Now while this is a prototype, it seems to work as expected(?) and I see no bottlenecks:
```python
In [1]: from skfem import *                                                                                            

In [2]: m = MeshTri().refined()                                                                                        

In [3]: basis = InteriorBasis(m, ElementTriP1())                                                                       

In [4]: from skfem.models.poisson import laplace                                                                       

In [5]: laplace.assemble(basis).todense()                                                                              
Out[5]: 
matrix([[ 1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  1. ,  0. ,  0. , -0.5,  0. ,  0. , -0.5,  0. ],
        [ 0. ,  0. ,  1. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. , -0.5, -0.5],
        [-0.5, -0.5,  0. ,  0. ,  2. ,  0. , -1. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  1. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. , -1. , -1. ,  4. , -1. , -1. ],
        [ 0. , -0.5,  0. , -0.5,  0. ,  0. , -1. ,  2. ,  0. ],
        [ 0. ,  0. , -0.5, -0.5,  0. ,  0. , -1. ,  0. ,  2. ]])
```
A practical implementation could (finally) use an additional flag to `assemble` which returns the unassembled triplet `(data, rows, cols)` that could be later modified via similar steps, maybe using a function in `skfem.utils`.

What you think?

**Comment by kinnala** [comment]
Here is a prototype with these ideas: https://github.com/kinnala/scikit-fem/pull/596

**Comment by gdmcbain** [comment]
Great!  

Rather than a flag though (cyclomatic complexity and a union return type-hint), I'd suggest factorization, as in `from_meshio` and `from_file`; one function does almost all the work while it's the other that's called routinely but the first can be called directly to get the raw data and indices when required. —And, right, I see that those are encapsulated as `UnassembledMatrix` in #596.

Besides cuda and PETSc, I'm also keeping an eye on [sparse.pydata.org](https://sparse.pydata.org) and [Dask](https://docs.dask.org/en/latest/array-sparse.html). It seems likely to me that Python will continue to accrete increasingly powerful numerical backends and that scikit-fem will be well placed to take advantage of these.

**Comment by gdmcbain** [comment]
On 

> The resulting matrix has the same spectral properties as the condensed *A*, so the number of iterations with Krylov methods will be the same, too.

I initially baulked at this as the condensed *A* obviously has `len(D)` less eigenvalues. The Dirichlet-modified matrix of full shape has a unit eigenvalue for each constrained degree of freedom; however, it turns out that in a Krylov scheme this is exactly cancelled by the modification of the right-hand side. This is sketched by Ern & Guermond in the reference given above.

The cases that i was previously haunted by weren't static solves but rather involved mass matrices: either generalized eigenvalue problems or unsteady evolution. The corresponding change to the mass matrix is a zero on the diagonal which makes it singular. The corresponding generalized eigenvalues are infinite—Dirichlet degrees of freedom having zero time constants, being 'algebraic' in the sense of DAEs. Those might be a problem even for the Krylov-like methods (Arnoldi) depending where in the spectrum one is looking but if it's nearer the origin than infinity it might be O. K.

**Comment by kinnala** [comment]
So maybe instead of using `coo` flag we should have an alternative to `Form.assemble`? Say `Form.unassemble` (or whatever)?

**Comment by gdmcbain** [comment]
Yeah, I think that that's consistent with the distinction between the `elemental` and `assemble` merhods.

&lsquo;Unassemble&rsquo; sounds a bit like an inverse; maybe&hellip;hmm, no, I don't know. `coo_data`?  Is there much to a `coo_matrix` other than this? I mean is mostly just a data-structure with data and indices and so not really much more than `UnassembledMatrix`?

**Comment by kinnala** [comment]
> Is there much to a `coo_matrix` other than this? I mean is mostly just a data-structure with data and indices and so not really much more than `UnassembledMatrix`?

Maybe, but I suppose it's not exactly the same because I think `scipy.sparse.coo_matrix` does summation of duplicates upon initialization. We have been also traditionally calling `coo_matrix.eliminate_zeros()` because in some cases there are many close-to-zero values in the resulting matrix.

Maybe rename `UnassembledMatrix` to `COOData` and then we could use `Form.coo_data`?

**Comment by kinnala** [comment]
Made some updates to #596.

You can do stuff like:
```python
In [7]: m = MeshTri().refined()                                                                                        

In [8]: basis = InteriorBasis(m, ElementTriP1())                                                                       

In [9]: laplace.coo_data(basis).enforce(m.boundary_nodes()).tocsr()                                                    
Out[9]: 
<9x9 sparse matrix of type '<class 'numpy.float64'>'
	with 13 stored elements in Compressed Sparse Row format>

In [10]: laplace.coo_data(basis).enforce(m.boundary_nodes()).tocsr().todense()                                         
Out[10]: 
matrix([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0., -1., -1.,  4., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])
```

**Comment by kinnala** [comment]
Example usage: https://github.com/kinnala/scikit-fem/pull/596/files#diff-95667c4df66488611725f70d1a0242f0a8f522a6eed0931e9117d1644ff40632R317

**Comment by nschloe** [comment]
Hopefully I'll have some time to check this out tomorrow.

**Comment by gdmcbain** [comment]
I'd say that the PR is WIP and that eventually the syntax would be more like that of `skfem.utils.condense`, as [above](https://github.com/kinnala/scikit-fem/issues/591#issuecomment-806409380)
```python
enforce(A, b, vals, D=mesh.boundary_nodes())
```
so instead of `skfem.apply_dirichlet(A, boundary_indices)` it'd only be necessary to insert `b` and prepend `D=` to the last argument, which isn't too bad.

(I wonder whether it would be reasonable to let the RHS `b` default to zero in [`condense`](https://github.com/kinnala/scikit-fem/blob/a88739744505ace72f59021400a548f3e16e0ded/skfem/utils.py#L359) and its forthcoming siblings?  `zeros_like` does appear fairly often in the second slot for `condense`.)

The _&lambda;_ is interesting but might be considered against the spirit of the finite element method since that's not necessarily limited to Lagrangian elements; in that sense, `projection` is the right thing to do.  But for simple cases one can get at `Mesh.p` or `InteriorBasis.doflocs`, yes; for example, ex14 can be simplified to
```python
u = solve(
    *condense(A, np.zeros(A.shape[0]), dirichlet(basis.doflocs), D=basis.find_dofs())
)
```
And for `ElementTriP1` the third argument, `x`, can even be replaced with `dirichlet(m.p)`.

I don't like the name `apply_dirichlet` so much as there are lots of ways to apply Dirichlet (condense, enforce, penalize, introduce Lagrange multiplier, Nitsche, &hellip;) and eventually all of these should be included (if only for pedagogical purposes), but pretty much they should share syntax.  And then perhaps an umbrella function which might indeed by called `apply_dirichlet`, like `minimize` and [`root`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.root.html#scipy.optimize.root) in `scipy.optimize` that takes a `method="condense"` kwarg.  Do you think &lsquo;condense&rsquo; and &lsquo;enforce&rsquo; are a reasonable balance of brevity and descriptiveness for &sect;&sect;8.4.2 & 8.4.3 of Ern & Guermond?

I haven't finished convincing myself that &sect;8.4.3 is the one true way, although 

> Also, the solution will include the values of all degrees of freedom, making postprocessing easier.

does have appeal for nonlinear (#119) and unsteady (#531) problems, especially if the nonlinear or unsteady solver is abstracted into a function.

**Comment by kinnala** [comment]
> One computational thing to note is that it is more efficient to eliminate rows in csr matrices as opposed to coo matrices.

I see your point, maybe it's possible to modify the CSR data structure directly to achieve a similar thing. Now that I kind of understand what's going on here I can try it out.

> I'd just like to set Dirichlet values!

I think "Dirichlet values" is not very exact terminology because it's only in the context of CG elements that setting Dirichlet values has anything to do with what's going on here.

I don't know why FEniCS decided to use `apply_dirichlet`. Maybe it's doing something else under the hood to deal with, e.g., H(div)-conforming elements?

**Comment by kinnala** [comment]
> I see your point, maybe it's possible to modify the CSR data structure directly to achieve a similar thing. Now that I kind of understand what's going on here I can try it out.

Modifying the CSR data structure would require detecting which values correspond to given rows. There is 

> Something like
> 
> ```python
> for i in dofs:
>     matrix.data[matrix.indptr[i] : matrix.indptr[i + 1]] = 0.0
> 
> d = matrix.diagonal()
> d[dofs] = 1.0
> ```
> 
> would set the rows to `I`, but perhaps one can do better than the python loop here. [I've added a feature request in scipy](https://github.com/scipy/scipy/issues/13746), but the above would already work well as a makeshift solution.

Alright, I'm a little slow. You already had a solution here and it remains to vectorize it.

**Comment by kinnala** [comment]
I'm currently working on vectorizing the above idea, will soon push to #596.

**Comment by kinnala** [comment]
In #596, `skfem.utils.enforce` should be now pretty much equal to `skfem.utils.condense` but using a different strategy.

E.g., this should work:
```python
from skfem import *
from skfem.models import laplace, unit_load
m = MeshTri().refined(3)
basis = InteriorBasis(m, ElementTriP1())
A = laplace.assemble(basis)
b = unit_load.assemble(basis)
x = solve(*enforce(A, b, D=m.boundary_nodes()))
```

**Comment by nschloe** [comment]
The more I think about this, the more I think that `condense` isn't very good. Consider the very first example in docs:
```python
from skfem import *
from skfem.models.poisson import laplace, unit_load

m = MeshTri().refined(4)

e = ElementTriP1()
basis = InteriorBasis(m, e)

A = asm(laplace, basis)
b = asm(unit_load, basis)

x = solve(*condense(A, b, I=m.interior_nodes()))

if __name__ == "__main__":
    from os.path import splitext
    from sys import argv
    from skfem.visuals.matplotlib import plot, savefig
   
    plot(m, x, shading='gouraud', colorbar=True)
    savefig(splitext(argv[0])[0] + '_solution.png')
```
First of all, from a numerical standpoint, `condense` does a few steps of Gaussian elimination. Why not let `spsolve` implicitly take care of it? That'd also save the rewrite in memory and the usual `u[interior_idx] = sol` that I see sometimes in skfem. Curiously, this is absent in the above plot, and I'm wondering how `plot(m, x)` can succeed: the mesh `m` has all nodes, `x` only the interior ones, right?

```python
from skfem import *
from skfem.models.poisson import laplace, unit_load

# MeshTri is a bit weird, MeshTri of _what_?
m = MeshTri().refined(4)

e = ElementTriP1()
basis = InteriorBasis(m, e)   # TODO find a better name for "Interior"

A = assemble(laplace, basis)
b = assemble(unit_load, basis)
apply_dirichlet(A, b, lambda x: x[0] ** 2 - 0.5, basis.boundary_dofs)

x = solve(A, b)

if __name__ == "__main__":
    # as above
    pass
```

**Comment by kinnala** [comment]
condense will pass on the boundary values and dofs to solve, which then expands the solution vector. So x actually contains also the boundary values.

In some cases you'd never want to turn a symmetric problem into unsymmetric one just for the sake of setting boundary conditions. People sometimes go to great lengths to preserve symmetry, to be able to use Cholesky decomposition instead of LU decomposition or more efficient iterative solvers or preconditioners.

However, while enforce is a great and a welcome addition to scikit-fem, all this is somewhat tangential the point of the library which is the creation of the matrices and not solving the resulting systems.

**Comment by gdmcbain** [comment]
> That'd also save the rewrite in memory and the usual `u[interior_idx] = sol` that I see sometimes in skfem. Curiously, this is absent in the above plot, and I'm wondering how `plot(m, x)` can succeed: the mesh m has all nodes, `x` only the interior ones, right?

The `u[interior_idx] = sol` was more often seen in skfem before #228 &lsquo;Make expand=True the default behavior&rsquo; (in `condense`), merged 2019-08-03; with `expand=True` it's no longer needed for static problems but does still arise in unsteady algorithms like

https://github.com/kinnala/scikit-fem/blob/56fe1564d39c6ae0ea94c98c4ace2f864e4db106/docs/examples/ex19.py#L84

I intend to look at trying `enforce` instead of `condense` next time I look at an initial-value problem #531.

For generalized eigenvalue problems, with a mass-matrix, I'm more skeptical of the benefits of enforce but will also take a look; I see that it has already been adopted in

https://github.com/kinnala/scikit-fem/blob/56fe1564d39c6ae0ea94c98c4ace2f864e4db106/docs/examples/ex21.py#L88

(although not very smoothly: see #609).

**Comment by gdmcbain** [comment]
For the primitive Orr&ndash;Sommerfeld equation (a complex nonhermitian generalized eigenvalue problem with symmetric positive-definite mass matrix) replacing

https://github.com/kinnala/scikit-fem/blob/56fe1564d39c6ae0ea94c98c4ace2f864e4db106/docs/examples/ex29.py#L122

which produces

![ex29.png](https://user-images.githubusercontent.com/973268/87859022-e0801d00-c93a-11ea-978f-b1930627010b.png)

with 
```python
pencil = enforce(stiffness, mass_matrix, D=walls)
```
fails badly:

![ex29](https://user-images.githubusercontent.com/1588947/113803867-c0caa680-97a0-11eb-96a4-d8178147404e.png)

**Comment by gdmcbain** [comment]
Some further investigation on enforcing Dirichlet conditions in generalized eigenvalue problems.  As perhaps the simplest test case, I'm taking (&nabla;*u*, &nabla;*v*) + (&part;/&part;*t*)(u, v) = 0 on 0 < _x_ < 1 with *u*' (0) = 0 and *u* (1) = 0: the cooling of a slab with insulated and cold faces.  The eigensolutions are *u* (*x, t*) = cos (*m*+&frac12;) &pi; *x* exp &minus;(*m* + &frac12;)&sup2;&pi;&sup2; for *m* = 0, 1, 2, &hellip;.

The simplest discretization is
```python
b = InteriorBasis(
  MeshLine().with_boundaries({"cold": lambda x: x[0] == 1.0}), 
  ElementLineP1())
```
for which `L = asm(laplace, b)` is `[[1, -1], [-1, 1]]` and `M = asm(mass, b)` is `[[2, 1], [1, 2]]/6`.

The condensed pencil is `[[1]]`, `[[1/3]]` which has sole eigenvalue &minus;3 which is a reasonable approximation of *s*<sub>0</sub> = &minus;(&pi;/2)&sup2; &doteq; &minus;2.467.  The condensed eigenvector is `[1]` which uncondenses as `[1, 0]` which is exactly equal to cos &pi;*x*/2 on the nodes.

The enforced pencil is `[[1, -1], [0, 1]]`, `[[2, 1], [0, 0]]/6`. The finite eigenpair is the same as in the condensed case but there's also an infinite eigenvalue with eigenfunction `[-1, 2]`.  The eigenfunction corresponding to the infinite eigenvalue does not satisfy the Dirichlet condition!  I think that this is correct though: the interpretation is that this mode would be forced to satisfy the Dirichlet condition infinitely quickly, i.e. with zero relaxation time.  The vector `[-1, 2]` is also *M*-orthogonal to `[1, 0]`.

That was still a little troubling, so I also considered penalization (Ern & Guermond 2004, &sect;8.4.4) which approximates the Dirichlet condition with a Robin:
```python
cold_basis = FacetBasis(b.mesh, b.elem, facets=b.mesh.boundaries["cold"])
epsilon = 1e-3
penalization = asm(mass, cold_basis) / epsilon

L_epsilon = L + penalization
```
i.e. the penalized stiffness matrix is `[[1, -1], [0, 1+1/ε]]` while the mass matrix is unchanged.  For *&epsilon;*&rarr;0 this has two finite eigenvalues: _s_ = &minus;3 + 27 *&epsilon;*/4 + O (*&epsilon;*&sup2;) and &minus;4/*&epsilon;* &minus; 9 + O (*&epsilon;*).  I didn't work out the eigenvectors analytically but numerically:
```python
(sl, sr), vr = eig(
        -L_epsilon.toarray(),
        M.toarray(),
        homogeneous_eigvals=True,
    )
```
gives `[-0.99999888, -0.00149887]` (which approximates `[1, 0]`) and `[-0.44801683,  0.89402512]` (which is a unit-normed approximation of `[-1, 2]`).  The penalized matrices and eigensolution approach the enforced ones as *&epsilon;*&rarr;0, so I conclude that enforce is correct.

However it does imply some special Dirichlet modes which do not satisfy the Dirichlet condition and which if not deemed actually &lsquo;spurious&rsquo; will at least have to be treated with care.  Of course, Krylov methods might avoid these.

(Another catch which fooled me for a while when I was testing `enforce` before penalization: `enforce` mutates!  I assume that that's deliberate for efficiency.)

**Comment by gdmcbain** [comment]
A quick look at unsteady problems.  Say a _&theta;_-method is used, as in 

https://github.com/kinnala/scikit-fem/blob/8f0f0be7290142ac6dafd8a19a909152f17f52ec/docs/examples/ex19.py#L65-L67

After condensing *L* and *M*, the iteration is 

(&frac13; + *&theta;h*) *u* = {&frac13; &minus; (1 &minus; *&theta;*)*h*} *u*<sub>old</sub>

which has eigenvalue (log *&lambda;*) / *h* = &minus;3 + 9(*&theta;* &minus;&frac12;)*h* + O(*h*&sup2;), which looks O. K.


In the enforced method, one time-step is:
<a href="https://www.codecogs.com/eqnedit.php?latex=\begin{bmatrix}&space;\frac{1}{3}&space;&plus;&space;\theta&space;h&space;&&space;\frac{1}{6}&space;-&space;\theta&space;h&space;\\&space;0&space;&&space;\theta&space;h&space;\end{bmatrix}&space;\begin{Bmatrix}&space;u_0&space;\\&space;u_1&space;\end{Bmatrix}&space;=&space;\begin{bmatrix}&space;\frac{1}{3}&space;-&space;(1-\theta)&space;h&space;&&space;\frac{1}{6}&space;&plus;&space;(1-\theta)&space;h&space;\\&space;0&space;&&space;-(1-\theta)&space;h&space;\end{bmatrix}&space;\begin{Bmatrix}&space;u_0&space;\\&space;u_1&space;\end{Bmatrix}_\mathrm{old}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\begin{bmatrix}&space;\frac{1}{3}&space;&plus;&space;\theta&space;h&space;&&space;\frac{1}{6}&space;-&space;\theta&space;h&space;\\&space;0&space;&&space;\theta&space;h&space;\end{bmatrix}&space;\begin{Bmatrix}&space;u_0&space;\\&space;u_1&space;\end{Bmatrix}&space;=&space;\begin{bmatrix}&space;\frac{1}{3}&space;-&space;(1-\theta)&space;h&space;&&space;\frac{1}{6}&space;&plus;&space;(1-\theta)&space;h&space;\\&space;0&space;&&space;-(1-\theta)&space;h&space;\end{bmatrix}&space;\begin{Bmatrix}&space;u_0&space;\\&space;u_1&space;\end{Bmatrix}_\mathrm{old}" title="\begin{bmatrix} \frac{1}{3} + \theta h & \frac{1}{6} - \theta h \\ 0 & \theta h \end{bmatrix} \begin{Bmatrix} u_0 \\ u_1 \end{Bmatrix} = \begin{bmatrix} \frac{1}{3} - (1-\theta) h & \frac{1}{6} + (1-\theta) h \\ 0 & -(1-\theta) h \end{bmatrix} \begin{Bmatrix} u_0 \\ u_1 \end{Bmatrix}_\mathrm{old}" /></a>


If *&theta;* = 1 (backward Euler), the Dirichlet condition is enforced at each step.  If &frac12; < *&theta;* < 1, any boundary data is successively damped; for *&theta;* = &frac12; (Crank&ndash;Nicolson) any boundary data flip-flops in sign and for lower *&theta;* it's amplified.  That's probably O. K. for &frac12; < *&theta;* < 1, and if the boundary data is zero then the other ordinate evolves exactly as in the condensed case.

**Comment by gdmcbain** [comment]
This does not seem to carry across to ex19 though:
```python
L = diffusivity * asm(laplace, basis)
M = asm(mass, basis)
enforce(L, M, D=basis.find_dofs())

dt = .01
print(f'dt = {dt} µs')
theta = 1.0  # backward Euler
A = M + theta * L * dt
B = M - (1 - theta) * L * dt

# transpose as splu prefers CSC
backsolve = splu(A.T).solve

u_init = (np.cos(np.pi * mesh.p[0, :] / 2 / halfwidth[0])
          * np.cos(np.pi * mesh.p[1, :] / 2 / halfwidth[1]))


def step(t: float,
         u: np.ndarray) -> Tuple[float, np.ndarray]:
    return t + dt, backsolve(B @ u)
```
produces
```
0.01, 0.947, -0.0097
0.02, 0.906, -0.0085
0.03, 0.868, -0.0071
0.04, 0.832, -0.0052
0.05, 0.798, -0.0025
0.06, 0.767, +0.0015
0.07, 0.739, +0.0070
0.08, 0.714, +0.0142
0.09, 0.693, +0.0232
0.10, 0.675, +0.0341
0.11, 0.659, +0.0467
0.12, 0.647, +0.0611
0.13, 0.638, +0.0772
0.14, 0.631, +0.0949
0.15, 0.627, +0.1142
0.16, 0.625, +0.1350
0.17, 0.626, +0.1572
0.18, 0.629, +0.1808
0.19, 0.635, +0.2058
0.20, 0.642, +0.2320
0.21, 0.652, +0.2595
0.22, 0.664, +0.2882
0.23, 0.677, +0.3182
0.24, 0.693, +0.3494
0.25, 0.710, +0.3819
0.26, 0.730, +0.4156
0.27, 0.751, +0.4506
```
which is diverging: the temperature at the centre (second column) stops decreasing and starts increasing after _t_ = 0.17.

Shame: the function `step` is _much_ simpler.  I'm not sure what's gone wrong here.

**Comment by gdmcbain** [comment]
Ah, of course:
```python
backsolve = splu(A.T).solve
```
the left stepping matrix `A` is no longer symmetric so can't just be transposed willy-nilly to avoid the 

> SparseEfficiencyWarning: splu requires CSC matrix format

Replacing that with `backsolve = splu(A).solve` makes it run O. K.
