### ISSUE TITLE
internal boundaries in with_boundaries

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#683]
Internal boundaries were queried in #336 and support added in #340.  I wanted to check that these were preserved in serialization #158 #261 under #680, but it appeared whereas they were supported by the old [`Mesh.define_boundary`](https://github.com/kinnala/scikit-fem/blob/0855dae117728588f269d968c8da4dbe06446d1b/skfem/mesh/mesh.py#L142-L144), this has been deprecated in favour of the (functional rather than mutating) [`Mesh.with_boundaries`](https://github.com/kinnala/scikit-fem/blob/0855dae117728588f269d968c8da4dbe06446d1b/skfem/mesh/mesh.py#L164-L165) which doesn't support them.

The problem is in 

https://github.com/kinnala/scikit-fem/blob/0855dae117728588f269d968c8da4dbe06446d1b/skfem/mesh/mesh.py#L180

which hardcodes `boundaries_only=True`.

Minimal example:
```python
m = MeshLine([0, 1, 2]).with_boundaries({"mid0": lambda x: x[0] == 1.0})
m.define_boundary("mid1", lambda x: x[0] == 1.0, boundaries_only=False)
```
Then `m.boundaries` is
> {'mid0': array([], dtype=int64), 'mid1': array([1])}

**Comment by kinnala** [comment]
I'm sorry that we are are back in square one regarding the interfaces. Because the new `Mesh` class was quite a big refactoring, I probably deleted the one test we had with `centreline` interface to cut some corners.

However, can we take a critical look at the use of these interfaces. I'd like to fully understand the use cases. Now that we have `probes`, I think the one-dimensional example is not meaningful anymore. How about higher dimensional examples? Is the main use case to integrate over interfaces? Is there something else?

I propose that we use a separate `Mesh.interfaces` field, in addition to `Mesh.subdomains` and `Mesh.boundaries`, to make it clear that it is sets of internal facets.

**Comment by gdmcbain** [comment]
> I'd like to fully understand the use cases. Now that we have probes, I think the one-dimensional example is not meaningful anymore? How about higher dimensional examples? Is the main use case to integrate over interfaces? Is there something else?

One use case is a hypersurface source, like a point-source but (*n* – 1)-dimensional; e.g. the line-load on a Kirchhoff plate mentioned in the original issue. That shows up as a linear form so it's kind of an integral, yes.

That might be the main use, but I'm also wondering about multiphysics problems in which a subprogram might be solved on a subdomain for which an interface is really a boundary.  There might be better ways to handle that though.

**Comment by kinnala** [comment]
I think `InteriorFacetBasis` can be used for creating mortar coupling between two parts of the mesh if you have an internal boundary.
