### ISSUE TITLE
no longer interpolate

### ISSUE THREAD

**Issue by gdmcbain** [kinnala/scikit-fem#697]
In #692 , 57d8e29 shows in 

https://github.com/kinnala/scikit-fem/blob/57d8e29962112c81585077c9c49bd36d483f2075/docs/examples/ex13.py#L66

that it's no longer necessary to `interpolate` a field passed in as a coefficient to the assembly of a form.  This issue is a reminder to propagate this to the rest of `docs/examples`, [as promised](https://github.com/kinnala/scikit-fem/pull/692/files#r695322028), once #692 is completed and merged.

**Comment by kinnala** [comment]
There was recently some confusion regarding the use of other finite elements as material data inside the forms. Let's say that `u` was defined using `fbasis_p3` instead of `fbasis`, then explicit call to `fbasis_p3.interpolate` is required because `assemble` would automatically call `fbasis.interpolate(u)` and not `fbasis_p3.interpolate(u)`.

The most common use case involves using same `fbasis` but I wonder if we start dropping `interpolate` in the examples, will it cause more confusion?

**Comment by gdmcbain** [comment]
Yes, I see what you mean.  I don't know&hellip;.  I don't think I'll get confused but it's hard to say for new users and I don't have any at the moment, maybe next year.  I think I'll withdraw this for now unless anyone else has a firmer opinion.  Thanks.
