### ISSUE TITLE
Add development enviroment deployment info

### ISSUE THREAD

**Issue by kinnala** [kinnala/scikit-fem#78]
I mainly use conda to manage my virtual environments.

It would be useful to have enviroments.yml file to quickly start developing on a new machine.

What about other approaches? Should we also include requirements.txt for pip-only users?

**Comment by kinnala** [comment]
Added the file https://github.com/kinnala/scikit-fem/blob/master/environment.yml

**Comment by gdmcbain** [comment]
That's a good idea.

At the moment I am by force of circumstance (Microsoft Windows&hellip;) using conda and am finding it pretty good, but previously in my native habitat of Debian GNU/Linux I had been pip-only and I didn't find the setting up of the development environment for scikit-fem to be at all difficult&mdash;of course that is very much a consequence of the deliberate design decision to restrict the number of dependencies, e.g. 
* in #29 eschewing `attrs` for the standard library's `typing.NamedTuple`
* unlike nschloe/meshio#305

The idea of having to maintain more than one specification of the development-dependencies doesn't appeal.  Unless conda can use pip's infrastructure or something common to the two instead of an environment.yml?  (I haven't looked into this at all.)
